language: go
go:
  - master

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

before_cache:
  - pwd
  - ls /tmp

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - bash <(curl -s https://codecov.io/bash)
